name: Continuous integration

on: [push, pull_request]

jobs:
  ci:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust:
          - nightly

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: ${{ matrix.rust }}
          target: x86_64-unknown-none, i686-unknown-none
          override: true
          components: rustfmt, clippy

      - name: Setup QEMU
        uses: docker/setup-qemu-action@v1
        with:
          image: tonistiigi/binfmt:latest
          platforms: amd64

      - name: Build as x86_64
        uses: actions-rs/cargo@v1
        with:
          command: build --target x86_64-unknown-none

      - name: Build as i686
        uses: actions-rs/cargo@v1
        with:
          command: build --target i686-unknown-none

      - name: Test
        uses: actions-rs/cargo@v1
        with:
          command: test

      - name: Rustfmt
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check

      - name: Clippy
        uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: -- -D warnings
