name: Continuous integration

on: [push, pull_request]

jobs:
  ci:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust:
          - nightly

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: ${{ matrix.rust }}
          override: true
          components: rust-src, rustfmt, clippy

      - name: Setup QEMU
        run: sudo apt-get install -y qemu-system-x86

      - name: Build as x86_64
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --target x86_64-unknown-none

      - name: Build as i686
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --target i686-unknown-none.json

      - name: Test
        uses: actions-rs/cargo@v1
        with:
          command: test

      - name: Rustfmt
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check

      - name: Clippy
        uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: -- -D warnings
